name: your_project_name
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - images/assets/Screenshot 2025-04-20 123239.png
    - images/assets/WhatsApp Image 2025-05-04 at 22.28.38_1329c385.jpg
    - images/assets/WhatsApp Image 2025-05-04 at 22.28.39_42666499.jpg
    - images/assets/WhatsApp Image 2025-05-04 at 22.28.39_dbdb6aca.jpg
    - images/assets/WhatsApp Image 2025-05-04 at 22.28.39_ea540aef.jpg
    - images/assets/WhatsApp Image 2025-05-04 at 23.23.14_6dc02be8.jpg
    - images/assets/WhatsApp Image 2025-05-04 at 23.23.14_9788e0c7.jpg
    - images/assets/WhatsApp Image 2025-05-04 at 23.23.14_ed782e36.jpg
    - images/assets/WhatsApp Image 2025-05-04 at 23.23.15_cad3fa3d.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "images/assets/Screenshot 2025-05-05 025737.png"
